version: '3.8'

services:
  celeb-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    # Load environment variables from file
    env_file:
      - .env
    restart: unless-stopped 