name: Deploy Celebrity Lookalike App to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy App
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Navigate to app directory
            cd /srv/celeb
            
            # Pull latest changes or clone if first time
            if [ -d "app" ]; then
              echo "Updating existing app..."
              cd app
              git pull origin main
            else
              echo "Cloning app for first time..."
              git clone https://github.com/${{ github.repository }}.git app
              cd app
            fi
            
            # Stop existing containers
            echo "Stopping existing containers..."
            docker-compose down || true
            
            # Build and start containers
            echo "Building and starting containers..."
            docker-compose build --no-cache
            docker-compose up -d
            
            # Show status
            echo "Deployment complete! Container status:"
            docker-compose ps
            
            # Show logs (last 20 lines)
            echo "Recent logs:"
            docker-compose logs --tail=20
          EOF

      - name: Verify Deployment
        run: |
          sleep 10
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /srv/celeb/app
            if docker-compose ps | grep -q "Up"; then
              echo "✅ Deployment successful! App is running."
            else
              echo "❌ Deployment failed! App is not running."
              docker-compose logs
              exit 1
            fi
          EOF 